#sonar.projectKey=your_project_key
#sonar.organization=your_organization
#sonar.login=admin
#sonar.password=AdminAdmin!23
sonar.host.url=http://localhost:2000
sonar.token=squ_bfa90a81387557d2c002634345d4b56db48412ea
sonar.sources=src/
sonar.tests=test/
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
