sonar.projectKey=tfg-daw-backend
sonar.projectName=Backend TFG
#sonar.organization=your_organization
#sonar.login=admin
#sonar.password=AdminAdmin!23
sonar.token=squ_d4814cd77c71f6a3366fe3fcf5eb6f4c12b53487
sonar.host.url=http://localhost:2000
sonar.sources=src/
sonar.tests=test/
sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
