openapi: 3.0.0
info:
  title: API de Productos
  version: 1.0.0
  description: API para crear, obtener, actualizar y eliminar productos.
servers:
  - url: http://localhost:3000/api/v1/products

paths:
  /products:
    get:
      tags: [Productos]
      summary: Obtener todos los productos
      responses:
        '200':
          description: Lista de productos obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      tags: [Productos]
      summary: Crear un nuevo producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        '201':
          description: Producto creado correctamente

  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [Productos]
      summary: Obtener producto por ID
      responses:
        '200':
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      tags: [Productos]
      summary: Actualizar producto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductUpdate'
      responses:
        '200':
          description: Producto actualizado correctamente
    delete:
      tags: [Productos]
      summary: Eliminar producto
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Producto eliminado correctamente

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        category:
          type: string
        imageUrl:
          type: string
    NewProduct:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        category:
          type: string
        imageUrl:
          type: string
    ProductUpdate:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        stock:
          type: integer
        category:
          type: string
        imageUrl:
          type: string
