openapi: 3.0.0
info:
  title: API de Usuarios
  version: 1.0.0
  description: API para crear, obtener, actualizar y eliminar usuarios.
servers:
  - url: http://localhost:3000/api/v1/users

paths:
  /users:
    get:
      tags: [Usuarios]
      summary: Obtener todos los usuarios
      responses:
        '200':
          description: Lista de usuarios obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
    post:
      tags: [Usuarios]
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: Usuario creado correctamente

  /users/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      tags: [Usuarios]
      summary: Obtener usuario por ID
      responses:
        '200':
          description: Usuario encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags: [Usuarios]
      summary: Actualizar usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserUpdate'
      responses:
        '200':
          description: Usuario actualizado correctamente
    delete:
      tags: [Usuarios]
      summary: Eliminar usuario
      responses:
        '200':
          description: Usuario eliminado correctamente

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        username:
          type: string
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum: [user, admin]
    NewUser:
      type: object
      required:
        - username
        - name
        - email
        - password
      properties:
        username:
          type: string
        name:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [user, admin]
          default: user
    UserUpdate:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
